export enum ActionType {
    GET_BOOKS_START = "GET_BOOKS_START",
    GET_BOOKS = "GET_BOOKS",
    GET_BOOKS_FAILED = "GET_BOOKS_FAILED",
    GET_CATEGORIES = "GET_CATEGORIES",
    GET_CATEGORIES_FAILED = "GET_CATEGORIES_FAILED",
    SAVE_BOOK = "SAVE_BOOK"
}